name: Merge develop to feature branches

on:
  push:
    branches:
      - develop

jobs:
  create-pull-requests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Get feature branches
        id: get_branches
        run: |
          branches=$(git branch -r | grep 'origin/feature/' | sed 's|origin/||')
          echo "::set-output name=branches::$branches"

      - name: Create pull requests
        uses: peter-evans/create-pull-request@v3
        with:
          source-branch: develop
          commit-message: 'Auto PR from develop to feature branches'
          title: 'Auto PR from develop to feature branches'
          body: 'This is an automated pull request from develop to feature branches.'
          branches: ${{ steps.get_branches.outputs.branches }}

  auto-approve:
    needs: create-pull-requests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Auto approve pull requests
        uses: hmarr/auto-approve-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  enable-auto-merge:
    needs: auto-approve
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Enable auto-merge
        uses: alexwilson/enable-github-automerge-action@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: MERGE # You can change this to SQUASH or REBASE if needed
