name: Merge develop to feature branches

on:
  push:
    branches:
      - develop

permissions:
  contents: write
  pull-requests: write
  actions: write

jobs:
  develop-to-features:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Fetch all branches
        run: git fetch --all

      - name: List remote branches
        run: git branch -r

      - name: Get feature branches
        id: get_branches
        run: |
          branches=$(git branch -r | grep 'origin/feature/' | sed 's|origin/||')
          echo "branches=$branches" >> $GITHUB_ENV
          echo "branches=$branches"

      - name: Debug feature branches
        run: |
          echo "Feature branches: ${{ env.branches }}"

      - name: Check for changes and handle conflicts
        run: |
          for branch in ${{ env.branches }}; do
            # Checkout the feature branch
            git checkout $branch
            git pull origin develop --rebase || true
            if [ -n "$(git status --porcelain)" ]; then
              echo "Changes detected in $branch"
              git add .
              git commit -m "Resolve merge conflicts"
            else
              echo "No changes detected in $branch"
            fi

            # Create PR branch and push changes
            pr_branch="${branch}-pr"
            git checkout -B $pr_branch origin/develop
            git push --set-upstream origin $pr_branch
          done

      - name: Create or update pull requests
        id: create_prs
        run: |
          for branch in ${{ env.branches }}; do
            # Create or update the PR branch based on 'develop'
            pr_branch="${branch}-pr"
            git checkout -B $pr_branch origin/develop

            # Create the pull request using GitHub CLI (gh)
            gh pr create --base develop --head $pr_branch --title "Auto PR from develop to $branch" --body "This is an automated pull request from develop to feature branch $branch."
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Auto approve pull requests
        if: steps.create_prs.outputs.pull-request-url
        run: |
          pr_url="${{ steps.create_prs.outputs.pull-request-url }}"
          pr_number=$(echo $pr_url | grep -oP '\d+$')
          gh pr review $pr_number --approve
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Enable auto-merge
        if: steps.create_prs.outputs.pull-request-url
        run: |
          pr_url="${{ steps.create_prs.outputs.pull-request-url }}"
          pr_number=$(echo $pr_url | grep -oP '\d+$')
          gh pr merge $pr_number --auto --merge
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
