name: Merge main to develop

on:
  push:
    branches:
      - main # Trigger when commits are pushed to the main branch

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-create-pr-from-main:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
    
    - name: Check if auto-merge is allowed for the repository
      id: check_auto_merge
      run: |
        # Check if allow_auto_merge is enabled for the repository
        allow_auto_merge=$(gh api -H "Accept: application/vnd.github.v3+json" /repos/${{ github.repository }} | jq '.allow_auto_merge')
        echo "allow_auto_merge=$allow_auto_merge" >> $GITHUB_ENV
    
    - name: Create PR for main to develop branch
      id: create_pr
      run: |
        pr_url=$(gh pr create --base develop --head main --title "Auto PR from main to develop" --body "This is an automated pull request from main to develop." | grep -oP 'https://github.com/\S+')
        echo "pr_url=$pr_url" >> $GITHUB_ENV
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Auto approve pull requests
      run: |
        # Get the PR URLs from the environment variable
        pr_number=$(echo ${{ env.pr_url }} | grep -oP '\d+$')
        # Auto-approve the PR
        gh pr review $pr_number --approve
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Merge pull requests
      run: |
        # Get the PR URLs from the environment variable
        pr_number=$(echo ${{ env.pr_url }} | grep -oP '\d+$')

        # Check if auto-merge is allowed
        allow_auto_merge=${{ env.allow_auto_merge }}
        if [[ $allow_auto_merge == "true" ]]; then
          # Merge the PR
          gh pr merge --auto $pr_number
        else
          echo "Auto-merge is not allowed for the repository. merge the PR manually."
          gh pr merge $pr_number --merge --admin --body "Merging PR #$pr_number."
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
        